[package]
name = "pixelflut-gaming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
fontdue = "0.8.0"
futures = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
threadpool = "1.8.1"
image = "0.24.7"
rand = { version = "0.8.5", features = [] }